import os

GMAIL_USERNAME = os.environ['MPC_GMAIL_USERNAME']
GMAIL_PASSWORD = os.environ['MPC_GMAIL_PASSWORD']
DB_NAME = os.environ['MPC_DB_NAME']
DB_USERNAME = os.environ['MPC_DB_USERNAME']
DB_PASSWORD = os.environ['MPC_DB_PASSWORD']
PHOTO_PATH = os.environ['MPC_PHOTO_PATH']
